"""Township America Python SDK — PLSS and Texas TXSS coordinate conversion.

Usage::

    from townshipamerica import TownshipAmerica

    ta = TownshipAmerica("your_api_key")
    result = ta.search("NW 25 24N 1E 6th Meridian")
    centroid = result.centroid
    print(centroid.geometry.latitude, centroid.geometry.longitude)

    # Parcel reports
    energy = ta.energy_report("25 24N 1E 6th Meridian")
    federal = ta.federal_land_report("NW 25 24N 1E 6th Meridian")
    texas = ta.texas_report("A-175 Reeves County")
"""

from .client import AsyncTownshipAmerica, TownshipAmerica
from .exceptions import (
    AuthenticationError,
    NotFoundError,
    PayloadTooLargeError,
    RateLimitError,
    ServerError,
    TownshipAmericaError,
    ValidationError,
)
from .models import (
    CriticalHabitatRow,
    CropHistory,
    Elevation,
    EnergyConstraints,
    EnergyLeaseRow,
    EnergyOperatorRow,
    EnergyOperatorsSection,
    EnergyOrphanedWellRow,
    EnergyPipelineRow,
    EnergyPipelinesSection,
    EnergyRenewableSiting,
    EnergyReport,
    EnergyRoyalties,
    EnergyRoyaltyItem,
    EnergySageGrouse,
    EnergySageGrouseHabitat,
    EnergySplitEstate,
    EnergySplitEstateSide,
    EnergySummary,
    EnergyWellRow,
    EnergyWells,
    EnergyWellsNearby,
    EntityRef,
    Feature,
    FeatureCollection,
    FeatureProperties,
    FederalLandReport,
    FederalLeaseRow,
    FireshedRow,
    FloodZoneRow,
    FracFocusRow,
    FracFocusSection,
    LatLng,
    MiningClaimRow,
    MultiPolygon,
    OrphanedWellRow,
    Point,
    Polygon,
    PublicAccessRow,
    ReportMeta,
    ReportParcel,
    RightOfWayRow,
    SectionEnvelope,
    SectionSource,
    SoilRow,
    SurfaceManagementRow,
    TexasAbstractRef,
    TexasActiveWellRow,
    TexasCoastalErosionRow,
    TexasDecline,
    TexasDeclineCurvePoint,
    TexasDeclineFit,
    TexasMonthlyVolume,
    TexasPendingPermitRow,
    TexasPipelineRow,
    TexasProduction,
    TexasProductionBlock,
    TexasProductionLease,
    TexasProductionSummary,
    TexasPsfLandRow,
    TexasReport,
    TexasStateAgencyLandRow,
    TexasStateLeaseRow,
    TexasStateUnitRow,
    TexasUplandLeaseRow,
    TexasWell,
    TexasWellLocation,
    TexasWellSeriesPoint,
    TexasWellSeriesUnit,
    TexasWellUnit,
    UnavailableSection,
    WetlandRow,
    WildfireRiskRow,
)

__all__ = [
    "TownshipAmerica",
    "AsyncTownshipAmerica",
    "TownshipAmericaError",
    "AuthenticationError",
    "NotFoundError",
    "PayloadTooLargeError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    "FeatureCollection",
    "Feature",
    "FeatureProperties",
    "Point",
    "Polygon",
    "MultiPolygon",
    # Shared report models
    "LatLng",
    "EntityRef",
    "SectionEnvelope",
    "UnavailableSection",
    "SectionSource",
    "ReportMeta",
    "ReportParcel",
    # Energy API
    "EnergyReport",
    "EnergySummary",
    "EnergyWells",
    "EnergyWellsNearby",
    "EnergyWellRow",
    "EnergyOrphanedWellRow",
    "EnergyLeaseRow",
    "EnergyOperatorRow",
    "EnergyOperatorsSection",
    "EnergyRoyalties",
    "EnergyRoyaltyItem",
    "EnergyPipelineRow",
    "EnergyPipelinesSection",
    "FracFocusRow",
    "FracFocusSection",
    "EnergyConstraints",
    "EnergySplitEstate",
    "EnergySplitEstateSide",
    "EnergySageGrouse",
    "EnergySageGrouseHabitat",
    "EnergyRenewableSiting",
    # Federal Land API
    "FederalLandReport",
    "SurfaceManagementRow",
    "FederalLeaseRow",
    "RightOfWayRow",
    "FloodZoneRow",
    "MiningClaimRow",
    "WetlandRow",
    "FireshedRow",
    "SoilRow",
    "OrphanedWellRow",
    "CriticalHabitatRow",
    "PublicAccessRow",
    "WildfireRiskRow",
    "CropHistory",
    "Elevation",
    # Texas API
    "TexasReport",
    "TexasStateLeaseRow",
    "TexasStateUnitRow",
    "TexasPsfLandRow",
    "TexasStateAgencyLandRow",
    "TexasUplandLeaseRow",
    "TexasActiveWellRow",
    "TexasPipelineRow",
    "TexasPendingPermitRow",
    "TexasCoastalErosionRow",
    "TexasProduction",
    "TexasProductionBlock",
    "TexasProductionLease",
    "TexasProductionSummary",
    "TexasAbstractRef",
    "TexasMonthlyVolume",
    "TexasWell",
    "TexasWellLocation",
    "TexasWellUnit",
    "TexasWellSeriesPoint",
    "TexasWellSeriesUnit",
    "TexasDecline",
    "TexasDeclineFit",
    "TexasDeclineCurvePoint",
]

from importlib.metadata import version as _pkg_version

try:
    __version__ = _pkg_version("townshipamerica")
except Exception:
    __version__ = "2.0.0"
